# fly.toml app configuration file generated for faye-proud-mountain-3845 on 2025-09-24T02:11:00Z

app = "faye-proud-mountain-3845"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  JWT_SECRET = "AnyhowFitness-SuperSecret-ChangeThis-InProduction-2024!"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.concurrency]]
  type = "connections"
  hard_limit = 1000
  soft_limit = 800

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048